server:
  port: 9090
spring:
  application:
      name: api-gateway
      
#  cloud: 
#    gateway:
#      enabled : true
#      routes:
#      - id: hr_service
#        uri: http://localhost:8091/
#        predicates:
#        - Path=/hr/**
#        
#      - id: emp_service
#        uri: http://localhost:8181/ #with load balance and eureka
#        predicates:
#        - Path=/employee/**
#        
#      - id: dept_service
#        uri: lb://localhost:8186/
#        predicates:
#        - Path=/dept/**
        
eureka:
  client:
      register-with-eureka: true
      service-url:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
        
management:
    endpoint:
        web:
          exposure:
            include:
            - '*'

      