server:
  port: 8091
  
spring:
  application:
     name : hr-service
     
     

eureka:
  client:
    register-with-eureka: true
    service-url : 
      defaultZone : ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
   
resilience4j.circuitbreaker:
    instances:
        hr-service:
            registerHealthIndicator: true
            slidingWindowSize: 5
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            #recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
